{% set name = "pysolar" %}
{% set version = "0.8-RC1" %}
{% set sha256 = "83a860e6d631cae95f6cc16598f9af707ebebf70172182acf93e486053edf03d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/pingswept/pysolar/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "
  noarch: python

requirements:
  host:
    - pip
    - python >= 3.5
  run:
    - python >= 3.5
    - numpy
    - pytz

test:
  imports:
    - Pysolar

about:
  home: http://pysolar.org/
  license: GPL-3.0
  license_family: GPL
  summary: 'A collection of Python libraries for simulating the irradiation of any point on earth by the sun'
  description: |
    Pysolar is a collection of Python libraries for simulating the irradiation of any point on earth by the sun.
    It includes code for extremely precise ephemeris calculations, and more.
  doc_url: http://docs.pysolar.org/en/latest/
  dev_url: https://github.com/pingswept/pysolar

extra:
  recipe-maintainers:
    - robintw
