{% set version = "0.6" %}

package:
  name: pysolar
  version: {{ version }}

source:
  url: https://github.com/pingswept/pysolar/archive/{{ version }}.tar.gz
  sha256: 244a6f3287a4483b78b705f14057bd48f27bcac2b25bef3a16d0449b9fa05f6e

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy
    - pytz

test:
  imports:
    - Pysolar

about:
  home: http://pysolar.org/
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: 'A collection of Python libraries for simulating the irradiation of any point on earth by the sun'
  description: |
    Pysolar is a collection of Python libraries for simulating the irradiation of any point on earth by the sun.
    It includes code for extremely precise ephemeris calculations, and more.
  doc_url: http://docs.pysolar.org/en/latest/
  dev_url: https://github.com/pingswept/pysolar

extra:
  recipe-maintainers:
    - robintw
