{% set version = "0.13" %}

package:
  name: pysolar
  version: {{ version }}

source:
  url: https://github.com/pingswept/pysolar/archive/{{ version }}.tar.gz
  sha256: fe1c230877d8d1598e16fcf6f2d740d32eccbdb4d8f8c77e96a1d9bf146a71d7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - numpy
    - pytz

test:
  imports:
    - pysolar

about:
  home: http://pysolar.org/
  license: GPL-3.0
  license_file: COPYING
  license_family: GPL
  summary: A collection of Python libraries for simulating the irradiation of any point on earth by the sun
  description: |
    Pysolar is a collection of Python libraries for simulating the irradiation of any point on earth by the sun.
    It includes code for extremely precise ephemeris calculations, and more.
  doc_url: http://docs.pysolar.org/en/latest/
  dev_url: https://github.com/pingswept/pysolar

extra:
  recipe-maintainers:
    - robintw
