{% set version = "0.7" %}

package:
  name: pysolar
  version: {{ version }}

source:
  url: https://github.com/pingswept/pysolar/archive/0.8-RC1.tar.gz
  sha256: e0ffef84197116a3172055505df34bc9620fd05809cbeaa14edc85fa07161f54

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - numpy
    - pytz

test:
  imports:
    - pysolar

about:
  home: http://pysolar.org/
  license: GPL-3.0
  license_family: GPL
  summary: 'A collection of Python libraries for simulating the irradiation of any point on earth by the sun'
  description: |
    Pysolar is a collection of Python libraries for simulating the irradiation of any point on earth by the sun.
    It includes code for extremely precise ephemeris calculations, and more.
  doc_url: http://docs.pysolar.org/en/latest/
  dev_url: https://github.com/pingswept/pysolar

extra:
  recipe-maintainers:
    - robintw
