travis:
  secure:
    BINSTAR_TOKEN: o9wX8Wasu8kFpzRGechcOHQ3S0XmIdXxdH/kI2egww7JsHlHE/yxv06FMLpkoLdT80s41ZExcuEtRDRyoEWpmb5tJxD6SR9n6VtzCt159OHyrh2+CsaPXw8OjkjfHfwG7s3QlrhFkMGyrQnftoslwsi+CJ75wRqVqe/NF8fydRvFR8p77Tjmd1rEiZFmFS79ohP+Pso5PAKVdVWJ/IlxnBXZ/CkyZgvl1iHweiuZmSSpA+/j4r1s0LbF45SoJPDhBHrMyTtwflj2PDLLyC2qIXpwPIsBblii0IFiX2QQGnatlptbbm0COGsUH4KCAZEwV3pVtv1H4GpT0cZvp+pvfDFIbazT6LaQUGR5eV3lk14kW6DtwSmABGii/eWwKfzT4um7RvIY40QFWlCknkTO9S3f7lfWAzXbuOZlTTY0DBmUVdgmL/gLuUGOOmAu4uyfLoOcudRxUAkg63F3vtgQ/9RfbnN7bjUfmq8uyXNanPHueYI5ofZt2+AlVMS2uBcwxK5IsmyzHHHfoCKloGwaevKDSSiQ5Faf+EPq7/h8NRCd36TOmHl1kBn+mdSC+mosdN5RRfCX74xRKY/ZqADcw6HPKLDWwxpCQgf3pzkufoHK8egYcNlpejB32hDK30mxT3n5ObRFM1EXHALtlYyErWsVNnPV5Fg5c4G1zBpj2xo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
