travis:
  secure:
    BINSTAR_TOKEN: rgaXd/mO8E9nhPhcpUfZtBRRwRYScOiKcSE//pskmVlQe7QfCoiBvWsbIUYAYzNLwcpfa6gTABhGmwb8VztbFjgWowsDEronkZhz+VscGIb0TmFPfY5dCRUadlkQhzJK537TvEPExJjpLoJvw4xkR16RLM4hwUYssNta11vMLRJqIxIebzGJhEk6pxv4fHONII9r0Ngr1An1DDjh3fqiXrUSuH6JE+FYyQOGo40d8p9NOChAEv5R7geynKG/rJ+DRYIiBltgFAIKfWBC2c6cDqMhAkK3ta3mFRgrzExgkGJIHuFnJPloOWLsnNkT8Qqs13c7yErhd006wwe0wuCo9S9nl5eMvbS8KPyp90yIhgJJDYQ+Q7tfpUjVuaQh7zzRRUIONUbhWTQ9ZP+KP7gCzgkGk0Wj+Ll6JZ/75byVN/QeMVgfK3rWZVxy+/D3bqYYlZCFJEKapHXa61pgjrV3Q0wWB12dk93zVw+TvL9Q4ebNnHRb03kOfSoJ3/MxnRNFe7t1kwySHmodaUmyZxqdSM4euc2Jzj3i0n4o7TY9ndL9nnt2ta4oY0S1ZM+uk8//Ib/3ntnVA3i49wSoxcuPLgOl0PkH8sneQfoFqD1wNca3ELgq8uJ4lb6HRJDi+yxDv3ApOozi4HLEj+Mqo9GQf+psVzRwICJ8E/TM1YYGOG0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
